# DDL ATUALIZADA NO MODELO SQL SERVER

create database UVV_CC3M;

use UVV_CC3M;

create table CIDADES(
CIDADE_ID INT PRIMARY KEY IDENTITY(1,1),
CIDADE_NOME VARCHAR(50) NOT NULL
);

create table BANCOS(
BANCO_ID INT PRIMARY KEY IDENTITY(1,1),
BANCO_SALDO FLOAT NOT NULL,
BANCO_NOME VARCHAR(50) NOT NULL
);

create table EMPRESAS(
EMPRESA_ID INT PRIMARY KEY IDENTITY(1,1),
EMPRESA_RAZ_SOC VARCHAR(50) NOT NULL,
EMPRESA_TIPO INT NOT NULL,
EMPRESA_CNPJ_CPF VARCHAR(20) NOT NULL,
EMPRESA_CEP VARCHAR(14) NOT NULL,
EMPRESA_RUA VARCHAR(50) NOT NULL,
EMPRESA_BAIRRO VARCHAR(50) NOT NULL,
EMPRESA_NUMERO INT,
EMPRESA_TELEFONE VARCHAR(15) NOT NULL,
EMPRESA_EMAIL VARCHAR(30) NOT NULL,
EMPRESA_CIDADE INT NOT NULL,
CONSTRAINT FK_CIDADES_EMPRESA FOREIGN KEY (EMPRESA_CIDADE)
REFERENCES CIDADES(CIDADE_ID)
);

create table CONTAS_PAGAR(
PAG_ID INT PRIMARY KEY IDENTITY(1,1),
PAG_VALOR FLOAT NOT NULL,
PAG_DATA_VENC DATE NOT NULL,
PAG_DATA_PAGAMENTO DATE,
PAG_COD_BARRA TEXT NOT NULL,
PAG_EMPRESA INT NOT NULL,
PAG_BANCO INT NOT NULL,
CONSTRAINT FK_EMPRESA_CONTASPAGAR FOREIGN KEY (PAG_EMPRESA)
references EMPRESAS(EMPRESA_ID),
CONSTRAINT FK_BANCO_CONTASPAGAR FOREIGN KEY (PAG_BANCO)
REFERENCES BANCOS(BANCO_ID)
);

create table CONTAS_RECEBER(
RECEB_ID INT PRIMARY KEY IDENTITY(1,1),
RECEB_VALOR FLOAT NOT NULL,
RECEB_DATA_VENC DATE NOT NULL,
RECEB_DATA_PAGAMENTO DATE,
RECEB_COD_BARRA TEXT NOT NULL,
RECEB_EMPRESA INT NOT NULL,
RECEB_BANCO INT NOT NULL,
CONSTRAINT FK_EMPRESA_CONTASRECEBER FOREIGN KEY (RECEB_EMPRESA)
REFERENCES EMPRESAS(EMPRESA_ID),
CONSTRAINT FK_BANCO_CONTASRECEBER FOREIGN KEY (RECEB_BANCO)
REFERENCES BANCOS(BANCO_ID)
);
